#include <utest.h>
#include <string.h>

UTEST_TEST_CASE(strcspn){
    EXPECT_EQUAL_UINT(strcspn("", ""), 0);
    EXPECT_EQUAL_UINT(strcspn("", "abc"), 0);
    EXPECT_EQUAL_UINT(strcspn("abc", ""), 3);
    EXPECT_EQUAL_UINT(strcspn("abc", "abc"), 0);
    EXPECT_EQUAL_UINT(strcspn("abc", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("abc", "b"), 1);
    EXPECT_EQUAL_UINT(strcspn("abc", "c"), 2);
    EXPECT_EQUAL_UINT(strcspn("abc", "ab"), 0);
    EXPECT_EQUAL_UINT(strcspn("abc", "ac"), 0);
    EXPECT_EQUAL_UINT(strcspn("abc", "bc"), 1);
    EXPECT_EQUAL_UINT(strcspn("hello", "helo"), 0);
    EXPECT_EQUAL_UINT(strcspn("hello", "h"), 0);
    EXPECT_EQUAL_UINT(strcspn("hello", "e"), 1);
    EXPECT_EQUAL_UINT(strcspn("hello", "l"), 2);
    EXPECT_EQUAL_UINT(strcspn("hello", "o"), 4);
    EXPECT_EQUAL_UINT(strcspn("hello", "xyz"), 5);
    EXPECT_EQUAL_UINT(strcspn("hello", " "), 5);
    EXPECT_EQUAL_UINT(strcspn("hello world", " "), 5);
    EXPECT_EQUAL_UINT(strcspn("hello world", "w"), 6);
    EXPECT_EQUAL_UINT(strcspn("12345", "12345"), 0);
    EXPECT_EQUAL_UINT(strcspn("12345", "1"), 0);
    EXPECT_EQUAL_UINT(strcspn("12345", "5"), 4);
    EXPECT_EQUAL_UINT(strcspn("12345", "54321"), 0);
    EXPECT_EQUAL_UINT(strcspn("12345", "6"), 5);
    EXPECT_EQUAL_UINT(strcspn("abc123", "123"), 3);
    EXPECT_EQUAL_UINT(strcspn("abc123", "abc"), 0);
    EXPECT_EQUAL_UINT(strcspn("123abc", "abc"), 3);
    EXPECT_EQUAL_UINT(strcspn("123abc", "123"), 0);
    EXPECT_EQUAL_UINT(strcspn("aaa", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("aaa", "b"), 3);
    EXPECT_EQUAL_UINT(strcspn("aabbcc", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("aabbcc", "b"), 2);
    EXPECT_EQUAL_UINT(strcspn("aabbcc", "c"), 4);
    EXPECT_EQUAL_UINT(strcspn("aabbcc", "d"), 6);
    EXPECT_EQUAL_UINT(strcspn("   hello", "h"), 3);
    EXPECT_EQUAL_UINT(strcspn("   hello", " "), 0);
    EXPECT_EQUAL_UINT(strcspn("   hello", "helo"), 3);
    EXPECT_EQUAL_UINT(strcspn("\t\n\vhello", "h"), 3);
    EXPECT_EQUAL_UINT(strcspn("\t\n\vhello", "\t\n\v"), 0);
    EXPECT_EQUAL_UINT(strcspn("test", "test"), 0);
    EXPECT_EQUAL_UINT(strcspn("test", "t"), 0);
    EXPECT_EQUAL_UINT(strcspn("test", "e"), 1);
    EXPECT_EQUAL_UINT(strcspn("test", "s"), 2);
    EXPECT_EQUAL_UINT(strcspn("test", "x"), 4);
    EXPECT_EQUAL_UINT(strcspn("prefixsuffix", "s"), 6);
    EXPECT_EQUAL_UINT(strcspn("prefixsuffix", "pre"), 0);
    EXPECT_EQUAL_UINT(strcspn("prefixsuffix", "fix"), 3);
    EXPECT_EQUAL_UINT(strcspn("ABC", "ABC"), 0);
    EXPECT_EQUAL_UINT(strcspn("ABC", "A"), 0);
    EXPECT_EQUAL_UINT(strcspn("ABC", "B"), 1);
    EXPECT_EQUAL_UINT(strcspn("ABC", "C"), 2);
    EXPECT_EQUAL_UINT(strcspn("ABC", "AB"), 0);
    EXPECT_EQUAL_UINT(strcspn("ABC", "AC"), 0);
    EXPECT_EQUAL_UINT(strcspn("ABC", "BC"), 1);
    EXPECT_EQUAL_UINT(strcspn("ABC", "D"), 3);
    EXPECT_EQUAL_UINT(strcspn("0123456789", "0123456789"), 0);
    EXPECT_EQUAL_UINT(strcspn("0123456789", "0"), 0);
    EXPECT_EQUAL_UINT(strcspn("0123456789", "5"), 5);
    EXPECT_EQUAL_UINT(strcspn("0123456789", "9"), 9);
    EXPECT_EQUAL_UINT(strcspn("0123456789", "a"), 10);
    EXPECT_EQUAL_UINT(strcspn("abcdefghijklmnopqrstuvwxyz", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("abcdefghijklmnopqrstuvwxyz", "z"), 25);
    EXPECT_EQUAL_UINT(strcspn("abcdefghijklmnopqrstuvwxyz", "m"), 12);
    EXPECT_EQUAL_UINT(strcspn("abcdefghijklmnopqrstuvwxyz", "0123456789"), 26);
    EXPECT_EQUAL_UINT(strcspn("a", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("a", "b"), 1);
    EXPECT_EQUAL_UINT(strcspn("a", "ab"), 0);
    EXPECT_EQUAL_UINT(strcspn("ab", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("ab", "b"), 1);
    EXPECT_EQUAL_UINT(strcspn("ab", "ab"), 0);
    EXPECT_EQUAL_UINT(strcspn("ab", "c"), 2);
    EXPECT_EQUAL_UINT(strcspn("xyz", "xyz"), 0);
    EXPECT_EQUAL_UINT(strcspn("xyz", "x"), 0);
    EXPECT_EQUAL_UINT(strcspn("xyz", "y"), 1);
    EXPECT_EQUAL_UINT(strcspn("xyz", "z"), 2);
    EXPECT_EQUAL_UINT(strcspn("xyz", "xy"), 0);
    EXPECT_EQUAL_UINT(strcspn("xyz", "xz"), 0);
    EXPECT_EQUAL_UINT(strcspn("xyz", "yz"), 1);
    EXPECT_EQUAL_UINT(strcspn("xyz", "w"), 3);
    EXPECT_EQUAL_UINT(strcspn("hello,world", ","), 5);
    EXPECT_EQUAL_UINT(strcspn("hello,world", ",."), 5);
    EXPECT_EQUAL_UINT(strcspn("path/to/file", "/"), 4);
    EXPECT_EQUAL_UINT(strcspn("path/to/file", "/\\"), 4);
    EXPECT_EQUAL_UINT(strcspn("lllll", "l"), 0);
    EXPECT_EQUAL_UINT(strcspn("lllll", "m"), 5);
    EXPECT_EQUAL_UINT(strcspn("lllll", "lm"), 0);
    EXPECT_EQUAL_UINT(strcspn("abcabc", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("abcabc", "b"), 1);
    EXPECT_EQUAL_UINT(strcspn("abcabc", "c"), 2);
    EXPECT_EQUAL_UINT(strcspn("abcabc", "d"), 6);
    EXPECT_EQUAL_UINT(strcspn("111222333", "1"), 0);
    EXPECT_EQUAL_UINT(strcspn("111222333", "2"), 3);
    EXPECT_EQUAL_UINT(strcspn("111222333", "3"), 6);
    EXPECT_EQUAL_UINT(strcspn("111222333", "4"), 9);
    EXPECT_EQUAL_UINT(strcspn("ABCDEF", "A"), 0);
    EXPECT_EQUAL_UINT(strcspn("ABCDEF", "F"), 5);
    EXPECT_EQUAL_UINT(strcspn("ABCDEF", "G"), 6);
    EXPECT_EQUAL_UINT(strcspn("ABCDEF", "ABC"), 0);
    EXPECT_EQUAL_UINT(strcspn("ABCDEF", "DEF"), 3);
    EXPECT_EQUAL_UINT(strcspn("   \t\n  ", "a"), 7);
    EXPECT_EQUAL_UINT(strcspn("   \t\n  ", " "), 0);
    EXPECT_EQUAL_UINT(strcspn("   \t\n  ", "\t"), 3);
    EXPECT_EQUAL_UINT(strcspn("   \t\n  ", "\n"), 4);
    EXPECT_EQUAL_UINT(strcspn("a", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("a", "b"), 1);
    EXPECT_EQUAL_UINT(strcspn("a", "ab"), 0);
    EXPECT_EQUAL_UINT(strcspn("ababab", "a"), 0);
    EXPECT_EQUAL_UINT(strcspn("ababab", "b"), 1);
    EXPECT_EQUAL_UINT(strcspn("ababab", "c"), 6);
    EXPECT_EQUAL_UINT(strcspn("xyzxyz", "x"), 0);
    EXPECT_EQUAL_UINT(strcspn("xyzxyz", "y"), 1);
    EXPECT_EQUAL_UINT(strcspn("xyzxyz", "z"), 2);
    EXPECT_EQUAL_UINT(strcspn("xyzxyz", "w"), 6);
    EXPECT_EQUAL_UINT(strcspn("test123", "0123456789"), 4);
    EXPECT_EQUAL_UINT(strcspn("123test", "0123456789"), 0);
    EXPECT_EQUAL_UINT(strcspn("test", "0123456789"), 4);
}
