#include <stdint.h>
#include <utest.h>

UTEST_TEST_CASE(fixed_width_types){
    EXPECT_EQUAL_UINT64(sizeof(int8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(int16_t), 2);
    EXPECT_EQUAL_UINT64(sizeof(int32_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(int64_t), 8);

    EXPECT_EQUAL_UINT64(sizeof(uint8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(uint16_t), 2);
    EXPECT_EQUAL_UINT64(sizeof(uint32_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(uint64_t), 8);
}

UTEST_TEST_CASE(integer_types){
#if defined(__i386__) || defined(__arm__)
    EXPECT_EQUAL_UINT64(sizeof(intptr_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(uintptr_t), 4);
#elif defined(__x86_64__) || defined(__amd64__)
    EXPECT_EQUAL_UINT64(sizeof(intptr_t), 8);
    EXPECT_EQUAL_UINT64(sizeof(uintptr_t), 8);
#elif defined(__aarch64__)
    EXPECT_EQUAL_UINT64(sizeof(intptr_t), 8);
    EXPECT_EQUAL_UINT64(sizeof(uintptr_t), 8);
#endif
    EXPECT_EQUAL_UINT64(sizeof(intmax_t), 8);
    EXPECT_EQUAL_UINT64(sizeof(uintmax_t), 8);
}

UTEST_TEST_CASE(fast_least_types){
    EXPECT_EQUAL_UINT64(sizeof(int_least8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(int_least16_t), 2);
    EXPECT_EQUAL_UINT64(sizeof(int_least32_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(int_least64_t), 8);

    EXPECT_EQUAL_UINT64(sizeof(uint_least8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(uint_least16_t), 2);
    EXPECT_EQUAL_UINT64(sizeof(uint_least32_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(uint_least64_t), 8);

#if defined(__i386__) || defined(__arm__)
    EXPECT_EQUAL_UINT64(sizeof(int_fast8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(int_fast16_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(int_fast32_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(int_fast64_t), 8);

    EXPECT_EQUAL_UINT64(sizeof(uint_fast8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast16_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast32_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast64_t), 8);
#elif defined(__x86_64__) || defined(__amd64__)
    EXPECT_EQUAL_UINT64(sizeof(int_fast8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(int_fast16_t), 8);
    EXPECT_EQUAL_UINT64(sizeof(int_fast32_t), 8);
    EXPECT_EQUAL_UINT64(sizeof(int_fast64_t), 8);

    EXPECT_EQUAL_UINT64(sizeof(uint_fast8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast16_t), 8);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast32_t), 8);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast64_t), 8);
#elif defined(__aarch64__)
    EXPECT_EQUAL_UINT64(sizeof(int_fast8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(int_fast16_t), 2);
    EXPECT_EQUAL_UINT64(sizeof(int_fast32_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(int_fast64_t), 8);

    EXPECT_EQUAL_UINT64(sizeof(uint_fast8_t), 1);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast16_t), 2);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast32_t), 4);
    EXPECT_EQUAL_UINT64(sizeof(uint_fast64_t), 8);
#endif
}
UTEST_TEST_CASE(integer_limits){
    // Integer Minimum Values
    EXPECT_EQUAL_INT8(INT8_MIN, 0x80);
    EXPECT_EQUAL_INT16(INT16_MIN, 0x8000);
    EXPECT_EQUAL_INT32(INT32_MIN, 0x80000000);
    EXPECT_EQUAL_INT64(INT64_MIN, 0x8000000000000000);

    // Integer Maximum Values
    EXPECT_EQUAL_INT8(INT8_MAX, 0x7F);
    EXPECT_EQUAL_INT16(INT16_MAX, 0x7FFF);
    EXPECT_EQUAL_INT32(INT32_MAX, 0x7FFFFFFF);
    EXPECT_EQUAL_INT64(INT64_MAX, 0x7FFFFFFFFFFFFFFF);

    // Unsigned Integer Maximum Values
    EXPECT_EQUAL_UINT8(UINT8_MAX, 0xFF);
    EXPECT_EQUAL_UINT16(UINT16_MAX, 0xFFFF);
    EXPECT_EQUAL_UINT32(UINT32_MAX, 0xFFFFFFFFU);
    EXPECT_EQUAL_UINT64(UINT64_MAX, 0xFFFFFFFFFFFFFFFFULL);

    // Integer Fast Values
#if defined(__i386__) || defined(__arm__)
    EXPECT_EQUAL_INT64(INT_FAST8_MIN, INT8_MIN);
    EXPECT_EQUAL_INT64(INT_FAST16_MIN, INT32_MIN);
    EXPECT_EQUAL_INT64(INT_FAST32_MIN, INT32_MIN);
    EXPECT_EQUAL_INT64(INT_FAST64_MIN, INT64_MIN);

    EXPECT_EQUAL_INT64(INT_FAST8_MAX, INT8_MAX);
    EXPECT_EQUAL_INT64(INT_FAST16_MAX, INT32_MAX);
    EXPECT_EQUAL_INT64(INT_FAST32_MAX, INT32_MAX);
    EXPECT_EQUAL_INT64(INT_FAST64_MAX, INT64_MAX);

    EXPECT_EQUAL_UINT64(UINT_FAST8_MAX, UINT8_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST16_MAX, UINT32_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST32_MAX, UINT32_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST64_MAX, UINT64_MAX);
#elif defined(__x86_64__) || defined(__amd64__)
    EXPECT_EQUAL_INT64(INT_FAST8_MIN, INT8_MIN);
    EXPECT_EQUAL_INT64(INT_FAST16_MIN, INT64_MIN);
    EXPECT_EQUAL_INT64(INT_FAST32_MIN, INT64_MIN);
    EXPECT_EQUAL_INT64(INT_FAST64_MIN, INT64_MIN);

    EXPECT_EQUAL_INT64(INT_FAST8_MAX, INT8_MAX);
    EXPECT_EQUAL_INT64(INT_FAST16_MAX, INT64_MAX);
    EXPECT_EQUAL_INT64(INT_FAST32_MAX, INT64_MAX);
    EXPECT_EQUAL_INT64(INT_FAST64_MAX, INT64_MAX);

    EXPECT_EQUAL_UINT64(UINT_FAST8_MAX, UINT8_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST16_MAX, UINT32_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST32_MAX, UINT32_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST64_MAX, UINT64_MAX);
#elif defined(__aarch64__)
    EXPECT_EQUAL_INT64(INT_FAST8_MIN, INT8_MIN);
    EXPECT_EQUAL_INT64(INT_FAST16_MIN, INT16_MIN);
    EXPECT_EQUAL_INT64(INT_FAST32_MIN, INT32_MIN);
    EXPECT_EQUAL_INT64(INT_FAST64_MIN, INT64_MIN);

    EXPECT_EQUAL_INT64(INT_FAST8_MAX, INT8_MAX);
    EXPECT_EQUAL_INT64(INT_FAST16_MAX, INT16_MAX);
    EXPECT_EQUAL_INT64(INT_FAST32_MAX, INT32_MAX);
    EXPECT_EQUAL_INT64(INT_FAST64_MAX, INT64_MAX);

    EXPECT_EQUAL_UINT64(UINT_FAST8_MAX, UINT8_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST16_MAX, UINT16_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST32_MAX, UINT32_MAX);
    EXPECT_EQUAL_UINT64(UINT_FAST64_MAX, UINT64_MAX);
#endif

    // Integer Least Values
    EXPECT_EQUAL_INT8(INT_LEAST8_MIN, INT8_MIN);
    EXPECT_EQUAL_INT16(INT_LEAST16_MIN, INT16_MIN);
    EXPECT_EQUAL_INT32(INT_LEAST32_MIN, INT32_MIN);
    EXPECT_EQUAL_INT64(INT_LEAST64_MIN, INT64_MIN);

    EXPECT_EQUAL_INT8(INT_LEAST8_MAX, INT8_MAX);
    EXPECT_EQUAL_INT16(INT_LEAST16_MAX, INT16_MAX);
    EXPECT_EQUAL_INT32(INT_LEAST32_MAX, INT32_MAX);
    EXPECT_EQUAL_INT64(INT_LEAST64_MAX, INT64_MAX);

    EXPECT_EQUAL_UINT8(UINT_LEAST8_MAX, UINT8_MAX);
    EXPECT_EQUAL_UINT16(UINT_LEAST16_MAX, UINT16_MAX);
    EXPECT_EQUAL_UINT32(UINT_LEAST32_MAX, UINT32_MAX);
    EXPECT_EQUAL_UINT64(UINT_LEAST64_MAX, UINT64_MAX);

    EXPECT_EQUAL_INT64(INTMAX_MIN, INT64_MIN);
    EXPECT_EQUAL_INT64(INTMAX_MAX, INT64_MAX);
    EXPECT_EQUAL_UINT64(UINTMAX_MAX, UINT64_MAX);

#if defined(__i386__) || defined(__arm__)
    EXPECT_EQUAL_INT64(INTPTR_MIN, INT32_MIN);
    EXPECT_EQUAL_INT64(INTPTR_MAX, INT32_MAX);
    EXPECT_EQUAL_UINT64(UINTPTR_MAX, UINT32_MAX);
#elif defined(__x86_64__) || defined(__amd64__)
    EXPECT_EQUAL_INT64(INTPTR_MIN, INT64_MIN);
    EXPECT_EQUAL_INT64(INTPTR_MAX, INT64_MAX);
    EXPECT_EQUAL_UINT64(UINTPTR_MAX, UINT64_MAX);
#elif defined(__aarch64__)
    EXPECT_EQUAL_INT64(INTPTR_MIN, INT64_MIN);
    EXPECT_EQUAL_INT64(INTPTR_MAX, INT64_MAX);
    EXPECT_EQUAL_UINT64(UINTPTR_MAX, UINT64_MAX);
#endif

#if defined(__i386__) || defined(__arm__)
    EXPECT_EQUAL_UINT64(SIZE_MAX, UINT32_MAX);
    EXPECT_EQUAL_INT64(PTRDIFF_MIN, INT32_MIN);
    EXPECT_EQUAL_INT64(PTRDIFF_MAX, INT32_MAX);
#elif defined(__x86_64__) || defined(__amd64__)
    EXPECT_EQUAL_UINT64(SIZE_MAX, UINT64_MAX);
    EXPECT_EQUAL_INT64(PTRDIFF_MIN, INT64_MIN);
    EXPECT_EQUAL_INT64(PTRDIFF_MAX, INT64_MAX);
#elif defined(__aarch64__)
    EXPECT_EQUAL_UINT64(SIZE_MAX, UINT64_MAX);
    EXPECT_EQUAL_INT64(PTRDIFF_MIN, INT64_MIN);
    EXPECT_EQUAL_INT64(PTRDIFF_MAX, INT64_MAX);
#endif
    EXPECT_EQUAL_INT(SIG_ATOMIC_MAX, INT32_MAX);
    EXPECT_EQUAL_INT(SIG_ATOMIC_MIN, INT32_MIN);
}
UTEST_TEST_SUITE(stdint){
    UTEST_RUN_TEST_CASE(fixed_width_types);
    UTEST_RUN_TEST_CASE(integer_types);
    UTEST_RUN_TEST_CASE(fast_least_types);
    UTEST_RUN_TEST_CASE(integer_limits);
}