#include <utest.h>
#include <string.h>
#include <errno.h>

UTEST_TEST_CASE(strerror){
#ifdef __aarch64__
    EXPECT_EQUAL_STRING(strerror(0), "Undefined error: 0");
    EXPECT_EQUAL_STRING(strerror(EPERM), "Operation not permitted");
    EXPECT_EQUAL_STRING(strerror(ENOENT), "No such file or directory");
    EXPECT_EQUAL_STRING(strerror(ESRCH), "No such process");
    EXPECT_EQUAL_STRING(strerror(EINTR), "Interrupted system call");
    EXPECT_EQUAL_STRING(strerror(EIO), "Input/output error");
    EXPECT_EQUAL_STRING(strerror(ENXIO), "Device not configured");
    EXPECT_EQUAL_STRING(strerror(E2BIG), "Argument list too long");
    EXPECT_EQUAL_STRING(strerror(ENOEXEC), "Exec format error");
    EXPECT_EQUAL_STRING(strerror(EBADF), "Bad file descriptor");
    EXPECT_EQUAL_STRING(strerror(ECHILD), "No child processes");
    EXPECT_EQUAL_STRING(strerror(EDEADLK), "Resource deadlock avoided");
    EXPECT_EQUAL_STRING(strerror(ENOMEM), "Cannot allocate memory");
    EXPECT_EQUAL_STRING(strerror(EACCES), "Permission denied");
    EXPECT_EQUAL_STRING(strerror(EFAULT), "Bad address");
    EXPECT_EQUAL_STRING(strerror(ENOTBLK), "Block device required");
    EXPECT_EQUAL_STRING(strerror(EBUSY), "Resource busy");
    EXPECT_EQUAL_STRING(strerror(EEXIST), "File exists");
    EXPECT_EQUAL_STRING(strerror(EXDEV), "Cross-device link");
    EXPECT_EQUAL_STRING(strerror(ENODEV), "Operation not supported by device");
    EXPECT_EQUAL_STRING(strerror(ENOTDIR), "Not a directory");
    EXPECT_EQUAL_STRING(strerror(EISDIR), "Is a directory");
    EXPECT_EQUAL_STRING(strerror(EINVAL), "Invalid argument");
    EXPECT_EQUAL_STRING(strerror(ENFILE), "Too many open files in system");
    EXPECT_EQUAL_STRING(strerror(EMFILE), "Too many open files");
    EXPECT_EQUAL_STRING(strerror(ENOTTY), "Inappropriate ioctl for device");
    EXPECT_EQUAL_STRING(strerror(ETXTBSY), "Text file busy");
    EXPECT_EQUAL_STRING(strerror(EFBIG), "File too large");
    EXPECT_EQUAL_STRING(strerror(ENOSPC), "No space left on device");
    EXPECT_EQUAL_STRING(strerror(ESPIPE), "Illegal seek");
    EXPECT_EQUAL_STRING(strerror(EROFS), "Read-only file system");
    EXPECT_EQUAL_STRING(strerror(EMLINK), "Too many links");
    EXPECT_EQUAL_STRING(strerror(EPIPE), "Broken pipe");
    EXPECT_EQUAL_STRING(strerror(EDOM), "Numerical argument out of domain");
    EXPECT_EQUAL_STRING(strerror(ERANGE), "Result too large");
    EXPECT_EQUAL_STRING(strerror(EAGAIN), "Resource temporarily unavailable");
    EXPECT_EQUAL_STRING(strerror(EWOULDBLOCK), "Resource temporarily unavailable");
    EXPECT_EQUAL_STRING(strerror(EINPROGRESS), "Operation now in progress");
    EXPECT_EQUAL_STRING(strerror(EALREADY), "Operation already in progress");
    EXPECT_EQUAL_STRING(strerror(ENOTSOCK), "Socket operation on non-socket");
    EXPECT_EQUAL_STRING(strerror(EDESTADDRREQ), "Destination address required");
    EXPECT_EQUAL_STRING(strerror(EMSGSIZE), "Message too long");
    EXPECT_EQUAL_STRING(strerror(EPROTOTYPE), "Protocol wrong type for socket");
    EXPECT_EQUAL_STRING(strerror(ENOPROTOOPT), "Protocol not available");
    EXPECT_EQUAL_STRING(strerror(EPROTONOSUPPORT), "Protocol not supported");
    EXPECT_EQUAL_STRING(strerror(ESOCKTNOSUPPORT), "Socket type not supported");
    EXPECT_EQUAL_STRING(strerror(ENOTSUP), "Operation not supported");
    EXPECT_EQUAL_STRING(strerror(EOPNOTSUPP), "Operation not supported");
    EXPECT_EQUAL_STRING(strerror(EPFNOSUPPORT), "Protocol family not supported");
    EXPECT_EQUAL_STRING(strerror(EAFNOSUPPORT), "Address family not supported by protocol family");
    EXPECT_EQUAL_STRING(strerror(EADDRINUSE), "Address already in use");
    EXPECT_EQUAL_STRING(strerror(EADDRNOTAVAIL), "Can't assign requested address");
    EXPECT_EQUAL_STRING(strerror(ENETDOWN), "Network is down");
    EXPECT_EQUAL_STRING(strerror(ENETUNREACH), "Network is unreachable");
    EXPECT_EQUAL_STRING(strerror(ENETRESET), "Network dropped connection on reset");
    EXPECT_EQUAL_STRING(strerror(ECONNABORTED), "Software caused connection abort");
    EXPECT_EQUAL_STRING(strerror(ECONNRESET), "Connection reset by peer");
    EXPECT_EQUAL_STRING(strerror(ENOBUFS), "No buffer space available");
    EXPECT_EQUAL_STRING(strerror(EISCONN), "Socket is already connected");
    EXPECT_EQUAL_STRING(strerror(ENOTCONN), "Socket is not connected");
    EXPECT_EQUAL_STRING(strerror(ESHUTDOWN), "Can't send after socket shutdown");
    EXPECT_EQUAL_STRING(strerror(ETOOMANYREFS), "Too many references: can't splice");
    EXPECT_EQUAL_STRING(strerror(ETIMEDOUT), "Operation timed out");
    EXPECT_EQUAL_STRING(strerror(ECONNREFUSED), "Connection refused");
    EXPECT_EQUAL_STRING(strerror(ELOOP), "Too many levels of symbolic links");
    EXPECT_EQUAL_STRING(strerror(ENAMETOOLONG), "File name too long");
    EXPECT_EQUAL_STRING(strerror(EHOSTDOWN), "Host is down");
    EXPECT_EQUAL_STRING(strerror(EHOSTUNREACH), "No route to host");
    EXPECT_EQUAL_STRING(strerror(ENOTEMPTY), "Directory not empty");
    EXPECT_EQUAL_STRING(strerror(EPROCLIM), "Too many processes");
    EXPECT_EQUAL_STRING(strerror(EUSERS), "Too many users");
    EXPECT_EQUAL_STRING(strerror(EDQUOT), "Disc quota exceeded");
    EXPECT_EQUAL_STRING(strerror(ESTALE), "Stale NFS file handle");
    EXPECT_EQUAL_STRING(strerror(EREMOTE), "Too many levels of remote in path");
    EXPECT_EQUAL_STRING(strerror(EBADRPC), "RPC struct is bad");
    EXPECT_EQUAL_STRING(strerror(ERPCMISMATCH), "RPC version wrong");
    EXPECT_EQUAL_STRING(strerror(EPROGUNAVAIL), "RPC prog. not avail");
    EXPECT_EQUAL_STRING(strerror(EPROGMISMATCH), "Program version wrong");
    EXPECT_EQUAL_STRING(strerror(EPROCUNAVAIL), "Bad procedure for program");
    EXPECT_EQUAL_STRING(strerror(ENOLCK), "No locks available");
    EXPECT_EQUAL_STRING(strerror(ENOSYS), "Function not implemented");
    EXPECT_EQUAL_STRING(strerror(EFTYPE), "Inappropriate file type or format");
    EXPECT_EQUAL_STRING(strerror(EAUTH), "Authentication error");
    EXPECT_EQUAL_STRING(strerror(ENEEDAUTH), "Need authenticator");
    EXPECT_EQUAL_STRING(strerror(EPWROFF), "Device power is off");
    EXPECT_EQUAL_STRING(strerror(EDEVERR), "Device error");
    EXPECT_EQUAL_STRING(strerror(EOVERFLOW), "Value too large to be stored in data type");
    EXPECT_EQUAL_STRING(strerror(EBADEXEC), "Bad executable (or shared library)");
    EXPECT_EQUAL_STRING(strerror(EBADARCH), "Bad CPU type in executable");
    EXPECT_EQUAL_STRING(strerror(ESHLIBVERS), "Shared library version mismatch");
    EXPECT_EQUAL_STRING(strerror(EBADMACHO), "Malformed Mach-o file");
    EXPECT_EQUAL_STRING(strerror(ECANCELED), "Operation canceled");
    EXPECT_EQUAL_STRING(strerror(EIDRM), "Identifier removed");
    EXPECT_EQUAL_STRING(strerror(ENOMSG), "No message of desired type");
    EXPECT_EQUAL_STRING(strerror(EILSEQ), "Illegal byte sequence");
    EXPECT_EQUAL_STRING(strerror(ENOATTR), "Attribute not found");
    EXPECT_EQUAL_STRING(strerror(EBADMSG), "Bad message");
    EXPECT_EQUAL_STRING(strerror(EMULTIHOP), "EMULTIHOP (Reserved)");
    EXPECT_EQUAL_STRING(strerror(ENODATA), "No message available on STREAM");
    EXPECT_EQUAL_STRING(strerror(ENOLINK), "ENOLINK (Reserved)");
    EXPECT_EQUAL_STRING(strerror(ENOSR), "No STREAM resources");
    EXPECT_EQUAL_STRING(strerror(ENOTSOCK), "Socket operation on non-socket");
    EXPECT_EQUAL_STRING(strerror(EPROTO), "Protocol error");
    EXPECT_EQUAL_STRING(strerror(ETIME), "STREAM ioctl timeout");
#else
    EXPECT_EQUAL_STRING(strerror(0), "Success");
    EXPECT_EQUAL_STRING(strerror(EPERM), "Operation not permitted");
    EXPECT_EQUAL_STRING(strerror(ENOENT), "No such file or directory");
    EXPECT_EQUAL_STRING(strerror(ESRCH), "No such process");
    EXPECT_EQUAL_STRING(strerror(EINTR), "Interrupted system call");
    EXPECT_EQUAL_STRING(strerror(EIO), "Input/output error");
    EXPECT_EQUAL_STRING(strerror(ENXIO), "No such device or address");
    EXPECT_EQUAL_STRING(strerror(E2BIG), "Argument list too long");
    EXPECT_EQUAL_STRING(strerror(ENOEXEC), "Exec format error");
    EXPECT_EQUAL_STRING(strerror(EBADF), "Bad file descriptor");
    EXPECT_EQUAL_STRING(strerror(ECHILD), "No child processes");
    EXPECT_EQUAL_STRING(strerror(EAGAIN), "Resource temporarily unavailable");
    EXPECT_EQUAL_STRING(strerror(ENOMEM), "Cannot allocate memory");
    EXPECT_EQUAL_STRING(strerror(EACCES), "Permission denied");
    EXPECT_EQUAL_STRING(strerror(EFAULT), "Bad address");
    EXPECT_EQUAL_STRING(strerror(ENOTBLK), "Block device required");
    EXPECT_EQUAL_STRING(strerror(EBUSY), "Device or resource busy");
    EXPECT_EQUAL_STRING(strerror(EEXIST), "File exists");
    EXPECT_EQUAL_STRING(strerror(EXDEV), "Invalid cross-device link");
    EXPECT_EQUAL_STRING(strerror(ENODEV), "No such device");
    EXPECT_EQUAL_STRING(strerror(ENOTDIR), "Not a directory");
    EXPECT_EQUAL_STRING(strerror(EISDIR), "Is a directory");
    EXPECT_EQUAL_STRING(strerror(EINVAL), "Invalid argument");
    EXPECT_EQUAL_STRING(strerror(ENFILE), "Too many open files in system");
    EXPECT_EQUAL_STRING(strerror(EMFILE), "Too many open files");
    EXPECT_EQUAL_STRING(strerror(ENOTTY), "Inappropriate ioctl for device");
    EXPECT_EQUAL_STRING(strerror(ETXTBSY), "Text file busy");
    EXPECT_EQUAL_STRING(strerror(EFBIG), "File too large");
    EXPECT_EQUAL_STRING(strerror(ENOSPC), "No space left on device");
    EXPECT_EQUAL_STRING(strerror(ESPIPE), "Illegal seek");
    EXPECT_EQUAL_STRING(strerror(EROFS), "Read-only file system");
    EXPECT_EQUAL_STRING(strerror(EMLINK), "Too many links");
    EXPECT_EQUAL_STRING(strerror(EPIPE), "Broken pipe");
    EXPECT_EQUAL_STRING(strerror(EDOM), "Numerical argument out of domain");
    EXPECT_EQUAL_STRING(strerror(ERANGE), "Numerical result out of range");
    EXPECT_EQUAL_STRING(strerror(EDEADLK), "Resource deadlock avoided");
    EXPECT_EQUAL_STRING(strerror(ENAMETOOLONG), "File name too long");
    EXPECT_EQUAL_STRING(strerror(ENOLCK), "No locks available");
    EXPECT_EQUAL_STRING(strerror(ENOSYS), "Function not implemented");
    EXPECT_EQUAL_STRING(strerror(ENOTEMPTY), "Directory not empty");
    EXPECT_EQUAL_STRING(strerror(ELOOP), "Too many levels of symbolic links");
    EXPECT_EQUAL_STRING(strerror(EWOULDBLOCK), "Resource temporarily unavailable");
    EXPECT_EQUAL_STRING(strerror(ENOMSG), "No message of desired type");
    EXPECT_EQUAL_STRING(strerror(EIDRM), "Identifier removed");
    EXPECT_EQUAL_STRING(strerror(ECHRNG), "Channel number out of range");
    EXPECT_EQUAL_STRING(strerror(EL2NSYNC), "Level 2 not synchronized");
    EXPECT_EQUAL_STRING(strerror(EL3HLT), "Level 3 halted");
    EXPECT_EQUAL_STRING(strerror(EL3RST), "Level 3 reset");
    EXPECT_EQUAL_STRING(strerror(ELNRNG), "Link number out of range");
    EXPECT_EQUAL_STRING(strerror(EUNATCH), "Protocol driver not attached");
    EXPECT_EQUAL_STRING(strerror(ENOCSI), "No CSI structure available");
    EXPECT_EQUAL_STRING(strerror(EL2HLT), "Level 2 halted");
    EXPECT_EQUAL_STRING(strerror(EBADE), "Invalid exchange");
    EXPECT_EQUAL_STRING(strerror(EBADR), "Invalid request descriptor");
    EXPECT_EQUAL_STRING(strerror(EXFULL), "Exchange full");
    EXPECT_EQUAL_STRING(strerror(ENOANO), "No anode");
    EXPECT_EQUAL_STRING(strerror(EBADRQC), "Invalid request code");
    EXPECT_EQUAL_STRING(strerror(EBADSLT), "Invalid slot");
    EXPECT_EQUAL_STRING(strerror(EILSEQ), "Invalid or incomplete multibyte or wide character");
#endif
}