#include <signal.h>
#include <utest.h>

UTEST_TEST_CASE(types) {
  EXPECT_EQUAL_UINT(sizeof(sig_atomic_t), sizeof(int));
#if defined(_QLIBC_SOURCE) || defined(__QLIBC__)
  EXPECT_EQUAL_UINT(sizeof(sighandler_t), sizeof(void *));
#elif defined(__GNUC__)
  EXPECT_EQUAL_UINT(sizeof(__sighandler_t), sizeof(void *));
#endif
}

UTEST_TEST_CASE(macros) {
  EXPECT_EQUAL_INT(SIG_DFL, 0);
  EXPECT_EQUAL_INT(SIG_IGN, 1);
  EXPECT_EQUAL_INT(SIG_ERR, -1);

  EXPECT_EQUAL_INT(SIGHUP, 1);
  EXPECT_EQUAL_INT(SIGINT, 2);
  EXPECT_EQUAL_INT(SIGQUIT, 3);
  EXPECT_EQUAL_INT(SIGILL, 4);
  EXPECT_EQUAL_INT(SIGTRAP, 5);
  EXPECT_EQUAL_INT(SIGABRT, 6);
  EXPECT_EQUAL_INT(SIGBUS, 7);
  EXPECT_EQUAL_INT(SIGFPE, 8);
  EXPECT_EQUAL_INT(SIGKILL, 9);
  EXPECT_EQUAL_INT(SIGUSR1, 10);
  EXPECT_EQUAL_INT(SIGSEGV, 11);
  EXPECT_EQUAL_INT(SIGUSR2, 12);
  EXPECT_EQUAL_INT(SIGPIPE, 13);
  EXPECT_EQUAL_INT(SIGALRM, 14);
  EXPECT_EQUAL_INT(SIGTERM, 15);
  EXPECT_EQUAL_INT(SIGSTKFLT, 16);
  EXPECT_EQUAL_INT(SIGCHLD, 17);
  EXPECT_EQUAL_INT(SIGCONT, 18);
  EXPECT_EQUAL_INT(SIGSTOP, 19);
  EXPECT_EQUAL_INT(SIGTSTP, 20);
  EXPECT_EQUAL_INT(SIGTTIN, 21);
  EXPECT_EQUAL_INT(SIGTTOU, 22);
  EXPECT_EQUAL_INT(SIGURG, 23);
  EXPECT_EQUAL_INT(SIGXCPU, 24);
  EXPECT_EQUAL_INT(SIGXFSZ, 25);
  EXPECT_EQUAL_INT(SIGVTALRM, 26);
  EXPECT_EQUAL_INT(SIGPROF, 27);
  EXPECT_EQUAL_INT(SIGWINCH, 28);
  EXPECT_EQUAL_INT(SIGIO, 29);
  EXPECT_EQUAL_INT(SIGPWR, 30);
  EXPECT_EQUAL_INT(SIGSYS, 31);
}

UTEST_TEST_SUITE(signal) {
  UTEST_RUN_TEST_CASE(types);
  UTEST_RUN_TEST_CASE(macros);
}