/* qlibc - A light-weight and portable C standard library
 * Copyright (C) 2025 Qiu Yixiang
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Constants for strerror for aarch64

ERROR(0, "Undefined error: 0"),
ERROR(EPERM, "Operation not permitted"),
ERROR(ENOENT, "No such file or directory"),
ERROR(ESRCH, "No such process"),
ERROR(EINTR, "Interrupted system call"),
ERROR(EIO, "Input/output error"),
ERROR(ENXIO, "Device not configured"),
ERROR(E2BIG, "Argument list too long"),
ERROR(ENOEXEC, "Exec format error"),
ERROR(EBADF, "Bad file descriptor"),
ERROR(ECHILD, "No child processes"),
ERROR(EDEADLK, "Resource deadlock avoided"),
ERROR(ENOMEM, "Cannot allocate memory"),
ERROR(EACCES, "Permission denied"),
ERROR(EFAULT, "Bad address"),
ERROR(ENOTBLK, "Block device required"),
ERROR(EBUSY, "Resource busy"),
ERROR(EEXIST, "File exists"),
ERROR(EXDEV, "Cross-device link"),
ERROR(ENODEV, "Operation not supported by device"),
ERROR(ENOTDIR, "Not a directory"),
ERROR(EISDIR, "Is a directory"),
ERROR(EINVAL, "Invalid argument"),
ERROR(ENFILE, "Too many open files in system"),
ERROR(EMFILE, "Too many open files"),
ERROR(ENOTTY, "Inappropriate ioctl for device"),
ERROR(ETXTBSY, "Text file busy"),
ERROR(EFBIG, "File too large"),
ERROR(ENOSPC, "No space left on device"),
ERROR(ESPIPE, "Illegal seek"),
ERROR(EROFS, "Read-only file system"),
ERROR(EMLINK, "Too many links"),
ERROR(EPIPE, "Broken pipe"),
ERROR(EDOM, "Numerical argument out of domain"),
ERROR(ERANGE, "Result too large"),
ERROR(EAGAIN, "Resource temporarily unavailable"),
ERROR(EWOULDBLOCK, "Resource temporarily unavailable"),
ERROR(EINPROGRESS, "Operation now in progress"),
ERROR(EALREADY, "Operation already in progress"),
ERROR(ENOTSOCK, "Socket operation on non-socket"),
ERROR(EDESTADDRREQ, "Destination address required"),
ERROR(EMSGSIZE, "Message too long"),
ERROR(EPROTOTYPE, "Protocol wrong type for socket"),
ERROR(ENOPROTOOPT, "Protocol not available"),
ERROR(EPROTONOSUPPORT, "Protocol not supported"),
ERROR(ESOCKTNOSUPPORT, "Socket type not supported"),
ERROR(ENOTSUP, "Operation not supported"),
ERROR(EOPNOTSUPP, "Operation not supported"),
ERROR(EPFNOSUPPORT, "Protocol family not supported"),
ERROR(EAFNOSUPPORT, "Address family not supported by protocol family"),
ERROR(EADDRINUSE, "Address already in use"),
ERROR(EADDRNOTAVAIL, "Can't assign requested address"),
ERROR(ENETDOWN, "Network is down"),
ERROR(ENETUNREACH, "Network is unreachable"),
ERROR(ENETRESET, "Network dropped connection on reset"),
ERROR(ECONNABORTED, "Software caused connection abort"),
ERROR(ECONNRESET, "Connection reset by peer"),
ERROR(ENOBUFS, "No buffer space available"),
ERROR(EISCONN, "Socket is already connected"),
ERROR(ENOTCONN, "Socket is not connected"),
ERROR(ESHUTDOWN, "Can't send after socket shutdown"),
ERROR(ETOOMANYREFS, "Too many references: can't splice"),
ERROR(ETIMEDOUT, "Operation timed out"),
ERROR(ECONNREFUSED, "Connection refused"),
ERROR(ELOOP, "Too many levels of symbolic links"),
ERROR(ENAMETOOLONG, "File name too long"),
ERROR(EHOSTDOWN, "Host is down"),
ERROR(EHOSTUNREACH, "No route to host"),
ERROR(ENOTEMPTY, "Directory not empty"),
ERROR(EPROCLIM, "Too many processes"),
ERROR(EUSERS, "Too many users"),
ERROR(EDQUOT, "Disc quota exceeded"),
ERROR(ESTALE, "Stale NFS file handle"),
ERROR(EREMOTE, "Too many levels of remote in path"),
ERROR(EBADRPC, "RPC struct is bad"),
ERROR(ERPCMISMATCH, "RPC version wrong"),
ERROR(EPROGUNAVAIL, "RPC prog. not avail"),
ERROR(EPROGMISMATCH, "Program version wrong"),
ERROR(EPROCUNAVAIL, "Bad procedure for program"),
ERROR(ENOLCK, "No locks available"),
ERROR(ENOSYS, "Function not implemented"),
ERROR(EFTYPE, "Inappropriate file type or format"),
ERROR(EAUTH, "Authentication error"),
ERROR(ENEEDAUTH, "Need authenticator"),
ERROR(EPWROFF, "Device power is off"),
ERROR(EDEVERR, "Device error"),
ERROR(EOVERFLOW, "Value too large to be stored in data type"),
ERROR(EBADEXEC, "Bad executable (or shared library)"),
ERROR(EBADARCH, "Bad CPU type in executable"),
ERROR(ESHLIBVERS, "Shared library version mismatch"),
ERROR(EBADMACHO, "Malformed Mach-o file"),
ERROR(ECANCELED, "Operation canceled"),
ERROR(EIDRM, "Identifier removed"),
ERROR(ENOMSG, "No message of desired type"),
ERROR(EILSEQ, "Illegal byte sequence"),
ERROR(ENOATTR, "Attribute not found"),
ERROR(EBADMSG, "Bad message"),
ERROR(EMULTIHOP, "EMULTIHOP (Reserved)"),
ERROR(ENODATA, "No message available on STREAM"),
ERROR(ENOLINK, "ENOLINK (Reserved)"),
ERROR(ENOSR, "No STREAM resources"),
ERROR(EPROTO, "Protocol error"),
ERROR(ETIME, "STREAM ioctl timeout")

