#include <errno.h>
#include <sys/wait.h>
#include <unistd.h>
#include <utest.h>

UTEST_TEST_CASE(wait_macros)
{
  EXPECT_EQUAL_UINT(WNOHANG, 1);
  EXPECT_EQUAL_UINT(WUNTRACED, 2);
  EXPECT_EQUAL_UINT(WCONTINUED, 8);

  EXPECT_TRUE(WIFEXITED(0x0000));
  EXPECT_EQUAL_INT(WEXITSTATUS(0x0000), 0);
  EXPECT_TRUE(WIFEXITED(0x0100));
  EXPECT_EQUAL_INT(WEXITSTATUS(0x0100), 1);
  EXPECT_TRUE(WIFEXITED(0xff00));
  EXPECT_EQUAL_INT(WEXITSTATUS(0xff00), 0xff);
  EXPECT_FALSE(WIFEXITED(0x0006));
  EXPECT_FALSE(WIFEXITED(0x057f));
  EXPECT_FALSE(WIFEXITED(0xffff));

  EXPECT_TRUE(WIFSIGNALED(0x0006));
  EXPECT_EQUAL_INT(WTERMSIG(0x0006), 6);
  EXPECT_TRUE(WIFSIGNALED(0x000b));
  EXPECT_EQUAL_INT(WTERMSIG(0x000b), 11);
  EXPECT_TRUE(WIFSIGNALED(0x0086));
  EXPECT_EQUAL_INT(WTERMSIG(0x0086), 6);
  EXPECT_FALSE(WIFSIGNALED(0x0000));
  EXPECT_FALSE(WIFSIGNALED(0x0100));
  EXPECT_FALSE(WIFSIGNALED(0x057f));
  EXPECT_FALSE(WIFSIGNALED(0xffff));
  EXPECT_FALSE(WIFSIGNALED(0x007f));

  EXPECT_TRUE(WCOREDUMP(0x0086));
  EXPECT_TRUE(WCOREDUMP(0x008b));
  EXPECT_FALSE(WCOREDUMP(0x0006));
  EXPECT_FALSE(WCOREDUMP(0x0000));
  EXPECT_FALSE(WCOREDUMP(0x057f));

  EXPECT_TRUE(WIFSTOPPED(0x057f));
  EXPECT_EQUAL_INT(WSTOPSIG(0x057f), 5);
  EXPECT_TRUE(WIFSTOPPED(0x137f));
  EXPECT_EQUAL_INT(WSTOPSIG(0x137f), 19);
  EXPECT_TRUE(WIFSTOPPED(0x7f7f));
  EXPECT_EQUAL_INT(WSTOPSIG(0x7f7f), 0x7f);
  EXPECT_TRUE(WIFSTOPPED(0x007f));
  EXPECT_EQUAL_INT(WSTOPSIG(0x007f), 0);
  EXPECT_FALSE(WIFSTOPPED(0x0000));
  EXPECT_FALSE(WIFSTOPPED(0x0006));
  EXPECT_FALSE(WIFSTOPPED(0xffff));

  EXPECT_TRUE(WIFCONTINUED(0xffff));
  EXPECT_FALSE(WIFCONTINUED(0x0000));
  EXPECT_FALSE(WIFCONTINUED(0x0100));
  EXPECT_FALSE(WIFCONTINUED(0x057f));
}

UTEST_TEST_CASE(wait)
{
  EXPECT_EQUAL_INT(wait(NULL), -1);
  EXPECT_EQUAL_INT(errno, ECHILD);
}